import type { SegmentedStartupRecoveryStageLimits } from "./audioPlaybackOrchestratorTypes";
import { createMigratingStorageKey } from "@/lib/storage-migration";

export const CURRENT_TIME_KEY = createMigratingStorageKey("current_time");
export const CURRENT_TIME_TRACK_ID_KEY = createMigratingStorageKey(
    "current_time_track_id",
);
export const AUDIO_LOAD_TIMEOUT_MS = 20_000;
export const AUDIO_LOAD_TIMEOUT_ASSET_BUILD_INFLIGHT_MS = 40_000;
export const AUDIO_LOAD_TIMEOUT_RETRIES = 1;
export const AUDIO_LOAD_RETRY_DELAY_MS = 350;
// Align the default startup retry window with the backend readiness budget
// while still permitting runtime overrides between the clamped bounds.
export const SEGMENTED_STARTUP_FALLBACK_TIMEOUT_DEFAULT_MS = 20_000;
export const SEGMENTED_STARTUP_FALLBACK_TIMEOUT_MIN_MS = 1_500;
export const SEGMENTED_STARTUP_FALLBACK_TIMEOUT_MAX_MS = 22_000;
export const SEGMENTED_STARTUP_ASSET_BUILD_TIMEOUT_FLOOR_MS = 10_000;
export const SEGMENTED_STARTUP_ON_DEMAND_TIMEOUT_BONUS_MS = 1_000;
export const SEGMENTED_STARTUP_ASSET_BUILD_TIMEOUT_BONUS_MS = 2_000;
export const SEGMENTED_STARTUP_RETRY_DELAY_MS = 450;
export const SEGMENTED_STARTUP_RETRY_BACKOFF_MAX_MS = 2_000;
export const SEGMENTED_STARTUP_RETRY_JITTER_RATIO = 0.35;
export const SEGMENTED_STARTUP_RECOVERY_WINDOW_MS = 15_000;
export const SEGMENTED_STARTUP_MAX_SESSION_RESETS = 1;
export const SEGMENTED_STARTUP_MANIFEST_READINESS_MAX_SESSION_RESETS = 1;
export const SEGMENTED_STARTUP_STAGE_MAX_ATTEMPTS: SegmentedStartupRecoveryStageLimits =
    {
        session_create: 2,
        manifest_readiness: 3,
        engine_load: 2,
    };
export const SEGMENTED_STARTUP_RETRY_BUDGET_MAX =
    (SEGMENTED_STARTUP_STAGE_MAX_ATTEMPTS.session_create +
        SEGMENTED_STARTUP_STAGE_MAX_ATTEMPTS.manifest_readiness +
        SEGMENTED_STARTUP_STAGE_MAX_ATTEMPTS.engine_load) *
    (SEGMENTED_STARTUP_MAX_SESSION_RESETS + 1);
export const SOUNDSPAN_RUNTIME_CONFIG_KEY = "__SOUNDSPAN_RUNTIME_CONFIG__";
export const SEGMENTED_STARTUP_FALLBACK_TIMEOUT_KEY =
    "SEGMENTED_STARTUP_FALLBACK_TIMEOUT_MS";
export const LISTEN_TOGETHER_SEGMENTED_PLAYBACK_ENABLED_KEY =
    "LISTEN_TOGETHER_SEGMENTED_PLAYBACK_ENABLED";
export const SEGMENTED_SESSION_PREWARM_ENABLED_KEY =
    "SEGMENTED_SESSION_PREWARM_ENABLED";
export const SEGMENTED_SESSION_PREWARM_ENABLED_DEFAULT = true;
export const TRACK_ERROR_SKIP_DELAY_MS = 1200;
export const TRANSIENT_TRACK_ERROR_RECOVERY_DELAY_MS = 450;
export const TRANSIENT_TRACK_ERROR_RECOVERY_WINDOW_MS = 15_000;
export const TRANSIENT_TRACK_ERROR_RECOVERY_MAX_ATTEMPTS = 4;
export const LISTEN_TOGETHER_FOLLOWER_RECOVERY_COOLDOWN_MS = 1_500;
export const STARTUP_PLAYBACK_RECOVERY_DELAY_MS = 1400;
export const STARTUP_PLAYBACK_RECOVERY_RECHECK_DELAY_MS = 900;
export const STARTUP_PLAYBACK_RECOVERY_MAX_RECHECKS = 2;
export const AUTOPLAY_INTENT_CONFLICT_WINDOW_MS = 3_000;
export const AUTO_MATCH_VIBE_RETRY_COOLDOWN_MS = 8000;
export const SEGMENTED_HEARTBEAT_INTERVAL_MS = 15_000;
export const SEGMENTED_HANDOFF_MAX_ATTEMPTS = 4;
export const SEGMENTED_HANDOFF_COOLDOWN_MS = 8_000;
export const SEGMENTED_HANDOFF_PROGRESS_RESET_MIN_DELTA_SEC = 3;
export const SEGMENTED_HANDOFF_RESET_STABLE_PLAYBACK_MS = 20_000;
export const SEGMENTED_HANDOFF_CIRCUIT_WINDOW_MS = 60_000;
export const SEGMENTED_HANDOFF_CIRCUIT_MAX_ATTEMPTS = 3;
export const SEGMENTED_HANDOFF_SESSION_CREATE_FALLBACK_COOLDOWN_MS = 3_000;
export const SEGMENTED_HANDOFF_SESSION_CREATE_FALLBACK_MAX_ATTEMPTS = 2;
export const SEGMENTED_REPRESENTATION_QUARANTINE_COOLDOWN_MS = 20_000;
export const SEGMENTED_CHUNK_QUARANTINE_RECOVERY_COOLDOWN_MS = 2_000;
export const SEGMENTED_CHUNK_QUARANTINE_MAX_ENTRIES = 96;
export const SEGMENTED_PREWARM_EXPIRY_GUARD_MS = 45_000;
export const SEGMENTED_PREWARM_RETRY_DELAY_MS = 1_000;
export const SEGMENTED_PREWARM_VALIDATION_TIMEOUT_MS = 10_000;
export const SEGMENTED_UNEXPECTED_STOP_STARTUP_GUARD_MIN_MS = 8_000;
export const SEGMENTED_UNEXPECTED_STOP_STARTUP_GUARD_MAX_MS = 20_000;
export const SEGMENTED_STARTUP_AUDIBLE_THRESHOLD_SEC = 0.2;
export const SEGMENTED_HEARTBEAT_BUFFER_TIMEOUT_MS = 7_000;
export const SEGMENTED_HEARTBEAT_FAILURE_THRESHOLD = 3;
export const SEGMENTED_HEARTBEAT_GUARDED_REFRESH_COOLDOWN_MS = 45_000;
export const SEGMENTED_COLD_START_REBUFFER_TIMEOUT_MS = 18_000;
export const SEGMENTED_COLD_START_REBUFFER_MAX_DEFERRALS = 2;
export const SEGMENTED_COLD_START_REBUFFER_MAX_POSITION_SEC = 12;
export const SEGMENTED_PAUSE_RECOVERY_DEBOUNCE_MS = 600;
export const SEGMENTED_PAUSE_RECOVERY_MIN_SILENCE_MS = 1200;
export const SEGMENTED_PAUSE_RECOVERY_MAX_BUFFERED_AHEAD_SEC = 1.0;
export const SEGMENTED_HANDOFF_LISTENER_BACKSTOP_MS = 20_000;
export const TRACK_END_WATCHDOG_TIMEOUT_MS = 2_000;
export const TRACK_END_WATCHDOG_BOUNDARY_SEC = 0.75;
export const AUDIO_ENGINE_MANIFEST_STALL_EVENTS = [
    "manifeststall",
    "manifest-stall",
] as const;

export const FORMAT_TO_CODEC: Record<string, string> = {
    mp3: "MP3",
    mp4: "AAC",
    flac: "FLAC",
    webm: "OPUS",
    wav: "WAV",
};
