import { execFile as execFileCallback } from "node:child_process";
import { join } from "node:path";
import { promisify } from "node:util";
import { Client } from "pg";

const execFile = promisify(execFileCallback);
const MIGRATION_TIMEOUT_MS = 120_000;
const SCALE_DATABASE_PATTERN = /^vibe_x2_\d+_\d+$/;

/** Remove Prisma-only schema selection from an administrative database URL. */
export function scaleAdminDatabaseUrl(databaseUrl: string): string {
    const parsed = new URL(databaseUrl);
    parsed.searchParams.delete("schema");
    return parsed.toString();
}

/** Reject a database name that was not generated by the integration bootstrap. */
export function assertSafeScaleDatabaseName(databaseName: string): void {
    if (!SCALE_DATABASE_PATTERN.test(databaseName)) {
        throw new Error("Scale integration database name is unsafe");
    }
}

/** Apply the repository's real Prisma migration chain to the throwaway database. */
export async function applyScaleMigrations(databaseUrl: string): Promise<void> {
    const backendRoot = join(__dirname, "..");
    const prismaBinary = join(backendRoot, "node_modules", ".bin", "prisma");
    await execFile(prismaBinary, ["migrate", "deploy"], {
        cwd: backendRoot,
        env: { ...process.env, DATABASE_URL: databaseUrl },
        timeout: MIGRATION_TIMEOUT_MS,
        maxBuffer: 4 * 1024 * 1024,
    });
}

/** Create the isolated database named by setupEnv and return its admin client. */
export async function createScaleDatabase(
    integrationDatabaseUrl: string,
    databaseName: string,
): Promise<Client> {
    assertSafeScaleDatabaseName(databaseName);
    const admin = new Client({
        connectionString: scaleAdminDatabaseUrl(integrationDatabaseUrl),
    });
    await admin.connect();
    try {
        await admin.query(`CREATE DATABASE "${databaseName}"`);
        return admin;
    } catch (error) {
        await admin.end();
        throw error;
    }
}

/** Force-drop one validated throwaway database and close its admin client. */
export async function dropScaleDatabase(
    admin: Client,
    databaseName: string,
): Promise<void> {
    assertSafeScaleDatabaseName(databaseName);
    try {
        await admin.query(
            `DROP DATABASE IF EXISTS "${databaseName}" WITH (FORCE)`,
        );
    } finally {
        await admin.end();
    }
}
